id: P010651
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS10
  title: སློབ་དཔོན་པད་འབྱུང་གི་སྨན་ཡིག་གཅེས་བཏུས
  author: ''
  volumes:
    707bd8635be346e8b87275941c65656c:
      image_group_id: I1PD423
      title: ''
      volume_number: 1
      total_pages: 478
      base_file: v001.txt
